# Disable SELinux
# - name: lookup acas password from AWS secrets manager secret in the current region
#   debug: msg="{{ (lookup('amazon.aws.aws_secret', 'acas_user_acas_database_password', region='us-east-1', profile='nimbus')| from_json).acas_database_password  }}"
- name: List of all hosts
  debug:
    msg: "{{ play_hosts }}"
- name: Disable selinux
  selinux:
    state: disabled
  notify: reboot
  when: ansible_os_family == 'RedHat' and local|default(false)|bool == false
  # failed_when ignores errors if selinux is not installed (added when running centos7 locally)
  failed_when: result.msg | default('ok', True) is not search('(^ok$|libselinux-python|(SELinux state changed))')
- name: Set hostname to {{ acas_fqdn }}
  hostname:
    name: "{{ acas_fqdn }}"
  notify: reboot
  when: local|default(false)|bool == false
- name: Reboot now
  meta: flush_handlers
- name: Install pip dependencies for other packages
  pip:
    name: [wheel]
    state: present
- name: Ensure group "acasadmins" exists
  group:
    name: acasadmins
    state: present
  tags: sync-users
- name: "Allow acasadmins to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^%acasadmins"
    line: "%acasadmins ALL=(ALL) NOPASSWD: ALL"
  tags: sync-users
- name: "Create user accounts and add users to groups"
  user:
    name: "{{ item }}"
    groups: "acasadmins"
  with_items: "{{ acas_server_admins }}"
  tags: sync-users
- name: Determine existing users
  shell: 'grep acasadmins /etc/group | cut -d: -f4 | tr "," "\n"'
  changed_when: false 
  register: existing_users
  tags: sync-users
- name: Determine removed users
  set_fact:
    removed_users: "{{ existing_users.stdout_lines | difference(acas_server_admins) }}"
  tags: sync-users
- name: Delete removed user accounts
  user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ removed_users }}"
  tags: sync-users
- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.acasadminkeys/' + item + '.pub') }}"
  with_items: "{{ acas_server_admins }}"
  tags: sync-users
