- name: Populate service facts (gets info about services already on the machine)
  service_facts:
- debug:
    msg: docker volume local persist already installed
  when: "'docker-volume-local-persist.service' in services"
- name: Install Local Persist (if configured). Download install script
  template: #TODO go back to orginal git repo and clone instead of using my local copy
    src: templates/install_local_persist.sh
    dest: "/tmp/install_local_persist.sh"
    mode: 0755
  when: "'docker-volume-local-persist.service' not in services"
- name: Install Local persist
  shell: /tmp/install_local_persist.sh
  when: "'docker-volume-local-persist.service' not in services"
- name: Remove local persist install script
  file: path=/tmp/install.sh state=absent
  when: "'docker-volume-local-persist.service' not in services"
